added staged deployment and tidy up
PA-NIHR-CRN/dte-event-handlers pull request #14
Opened 2023-11-08 23:48 UTC by paddyduff31

2023-11-09 09:36 UTC, Jaffacakes82 requested changes

2023-11-09 09:36 UTC, Jaffacakes82 commented on .github/workflows/staged_deployment.yml
> +          dotnet lambda deploy-function --region ${{ secrets.AWS_REGION }} -pl ./src/CognitoCustomMessageProcessor crnccd-lambda-dev-dte-cognito-custom-message-processor --function-role crnccd-iam-de
Lets separate this out a bit.

Let's have a stage for 'Built, Test and Package'

Then deployment stages for DEV -> PROD, that download that package and use dotnet lambda deploy-function.

2023-11-09 09:38 UTC, Jaffacakes82 commented
Suggest we de-activate our manual build and deploy workflows, in favour of using the staged one. Looks like we already have a PR Build and Test which is good 👍

2023-11-09 11:29 UTC, paddyduff31 commented
> Suggest we de-activate our manual build and deploy workflows, in favour of using the staged one. Looks like we already have a PR Build and Test which is good 👍

@Jaffacakes82 my only concern with removing this entirely is when we have multiple pieces of work going on at once and we need to use different environments for streams of work.  For example MFA work was in UAT and client was still testing so we used OAT for CMS work, then I even had to use QA for general tickets being prioritised and I was deploying from each branch to the environment.  Staged deployment would not allow for this...thoughts?

2023-11-10 17:16 UTC, ynasser25 commented
ive updated the staged deployment to allow selection between either cognito-custom-message-processor or scheduled-jobs then it will deploy through all envs, but doing this means it wont auto deploy all on merge to main you will have to select the workflow and app name to run the staged deployment

2024-03-08 15:43 UTC, con-nihr commented
> > Suggest we de-activate our manual build and deploy workflows, in favour of using the staged one. Looks like we already have a PR Build and Test which is good 👍
> 
> @Jaffacakes82 my only concern with removing this entirely is when we have multiple pieces of work going on at once and we need to use different environments for streams of work. For example MFA work was in UAT and client was still testing so we used OAT for CMS work, then I even had to use QA for general tickets being prioritised and I was deploying from each branch to the environment. Staged deployment would not allow for this...thoughts?

I think that's valid. We do use environments in a non-staged way from time to time.

What you have described would normally be tackled with feature flags, but we need to have a better process, discipline, and architecture around them so that parallel changes are de-risked to the point that we can deploy to other environments with confidence knowing that the feature flags will hide the effect of the optional behaviour completely.

Is a fully staged approach extracting as much value as possible out of the four environments?
Is pushing a change through Dev and QA to get it into UAT, making full use of Dev and QA?

2024-03-08 15:43 UTC, con-nihr requested changes

2024-03-08 15:43 UTC, con-nihr commented on .github/workflows/staged_deployment.yml
> +  deply_uat:
typo

2024-03-08 15:43 UTC, con-nihr commented on .github/workflows/staged_deployment.yml
> +    needs: deply_dev
typo

2024-03-08 15:53 UTC, paddyduff31 commented
> > > Suggest we de-activate our manual build and deploy workflows, in favour of using the staged one. Looks like we already have a PR Build and Test which is good 👍
> > 
> > 
> > @Jaffacakes82 my only concern with removing this entirely is when we have multiple pieces of work going on at once and we need to use different environments for streams of work. For example MFA work was in UAT and client was still testing so we used OAT for CMS work, then I even had to use QA for general tickets being prioritised and I was deploying from each branch to the environment. Staged deployment would not allow for this...thoughts?
> 
> I think that's valid. We do use environments in a non-staged way from time to time.
> 
> What you have described would normally be tackled with feature flags, but we need to have a better process, discipline, and architecture around them so that parallel changes are de-risked to the point that we can deploy to other environments with confidence knowing that the feature flags will hide the effect of the optional behaviour completely.
> 
> Is a fully staged approach extracting as much value as possible out of the four environments? Is pushing a change through Dev and QA to get it into UAT, making full use of Dev and QA?

Yeah that's a fair point, I understand why Joe was keen on the staged process to keep everything in unison and I see value in that, Do you think it would be better to deploy to all Dev environments(dev and tet), then a check before moving to staging(UAT) and another check before production(OAT and prod)? So 3 stages?

2024-03-08 16:02 UTC, ynasser25 requested changes
the staged deployment workflow itself looks good and will work as intended, the only comment is to update the actions themselves to work with node20 so you dont get all those warnings when the workflow is run:
actions/checkout@v2 - actions/checkout@v4
aws-actions/configure-aws-credentials@v1 - aws-actions/configure-aws-credentials@v4
actions/setup-dotnet@v1 - actions/setup-dotnet@v4


and also the latest dotnet build is showing errors that need to be reviewed

2024-03-08 16:07 UTC, con-nihr commented
> > > > Suggest we de-activate our manual build and deploy workflows, in favour of using the staged one. Looks like we already have a PR Build and Test which is good 👍
> > > 
> > > 
> > > @Jaffacakes82 my only concern with removing this entirely is when we have multiple pieces of work going on at once and we need to use different environments for streams of work. For example MFA work was in UAT and client was still testing so we used OAT for CMS work, then I even had to use QA for general tickets being prioritised and I was deploying from each branch to the environment. Staged deployment would not allow for this...thoughts?
> > 
> > 
> > I think that's valid. We do use environments in a non-staged way from time to time.
> > What you have described would normally be tackled with feature flags, but we need to have a better process, discipline, and architecture around them so that parallel changes are de-risked to the point that we can deploy to other environments with confidence knowing that the feature flags will hide the effect of the optional behaviour completely.
> > Is a fully staged approach extracting as much value as possible out of the four environments? Is pushing a change through Dev and QA to get it into UAT, making full use of Dev and QA?
> 
> Yeah that's a fair point, I understand why Joe was keen on the staged process to keep everything in unison and I see value in that, Do you think it would be better to deploy to all Dev environments(dev and tet), then a check before moving to staging(UAT) and another check before production(OAT and prod)? So 3 stages?

Have we decoupled the build from deployment?

Build 1
Deploy to Dev and Test.

Build 2 in progress.
...
Deploy to Dev and Test.

Build 1 - Deploy to UAT.

Build 3 in progress.
Deploy to Dev.

Build 1 - Deploy to Production.

Dev = Build 3
Test = Build 2
UAT = Build 1
Prod = Build 1

Build 1 has been through Dev, Test, UAT and Prod in sequence, but putting it into UAT & Prod at a later time has not wiped out the lower environments on the way there.

2024-03-08 16:59 UTC, paddyduff31 commented
@con-nihr yes build and deployment decoupled.  I have updated the actions.

2024-03-08 17:01 UTC, paddyduff31 commented
@con-nihr not sure if there is an action on your comment or not?

2026-04-23 14:26 UTC, closed without merging